# Generated by Django 5.1 on 2026-05-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCorrelativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(default='F-', max_length=10)),
                ('current_number', models.IntegerField(default=0)),
                ('number_length', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'ConfiguracionCorrelativo',
            },
        ),
        migrations.CreateModel(
            name='Configuracioniva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ConfiguracionIVA',
            },
        ),
        migrations.CreateModel(
            name='Tipodocumentofiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('obligatorio', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TipoDocumentoFiscal',
            },
        ),
    ]
