# Generated by Django 5.1 on 2026-05-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(default='Mi Empresa', max_length=255, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('rif', models.CharField(blank=True, max_length=20, null=True, verbose_name='RIF / ID Fiscal')),
                ('telefono', models.CharField(blank=True, help_text='Número para recibir notificaciones de pedidos.', max_length=50, null=True, verbose_name='Teléfono de la Empresa')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/', verbose_name='Logo de la Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de la Empresa',
                'verbose_name_plural': 'Configuración de la Empresa',
            },
        ),
        migrations.AlterModelOptions(
            name='configuracioncorrelativo',
            options={'verbose_name': 'Configuración de Correlativo', 'verbose_name_plural': 'Configuraciones de Correlativos'},
        ),
        migrations.AlterModelOptions(
            name='configuracioniva',
            options={'verbose_name': 'Configuración de IVA', 'verbose_name_plural': 'Configuraciones de IVA'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumentofiscal',
            options={'verbose_name': 'Tipo de Documento Fiscal', 'verbose_name_plural': 'Tipos de Documentos Fiscales'},
        ),
        migrations.AlterField(
            model_name='configuracioncorrelativo',
            name='current_number',
            field=models.IntegerField(default=0, help_text='El último número de factura utilizado.', verbose_name='Número Actual'),
        ),
        migrations.AlterField(
            model_name='configuracioncorrelativo',
            name='number_length',
            field=models.IntegerField(default=3, help_text='Número de dígitos para el correlativo (ej: 3 para 001).', verbose_name='Longitud del Número'),
        ),
        migrations.AlterField(
            model_name='configuracioncorrelativo',
            name='prefijo',
            field=models.CharField(default='F-', help_text='Prefijo para el número de factura (ej: F-).', max_length=10, verbose_name='Prefijo'),
        ),
        migrations.AlterField(
            model_name='configuracioniva',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='configuracioniva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='configuracioniva',
            name='nombre',
            field=models.CharField(blank=True, help_text='Ej: IVA General, IVA Reducido', max_length=20, null=True, verbose_name='Nombre del IVA'),
        ),
        migrations.AlterField(
            model_name='configuracioniva',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje (%)'),
        ),
        migrations.AlterField(
            model_name='tipodocumentofiscal',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipodocumentofiscal',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipodocumentofiscal',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipodocumentofiscal',
            name='obligatorio',
            field=models.BooleanField(default=False, verbose_name='Obligatorio'),
        ),
    ]
