# Generated by Django 5.1 on 2026-05-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configuracionempresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True, verbose_name='Código ISO 4217')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('simbolo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Símbolo')),
                ('es_predeterminada', models.BooleanField(default=False, verbose_name='Es moneda base')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'Moneda',
                'ordering': ['-es_predeterminada', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('tasa', models.DecimalField(decimal_places=6, help_text='Tasa: 1 unidad de la moneda = tasa unidades de la moneda base.', max_digits=20, verbose_name='Tasa')),
                ('fuente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuente')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_cambio', to='configuracion.moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'db_table': 'TasaCambio',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['moneda', 'fecha'], name='idx_moneda_fecha')],
            },
        ),
    ]
