# Generated by Django 5.1 on 2026-09-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_moneda_tasacambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='prefijo_numero_control',
            field=models.CharField(
                default='CTRL-',
                help_text='Prefijo para el número de control SENIAT (ej: CTRL-, NC-).',
                max_length=10,
                verbose_name='Prefijo Número de Control',
            ),
        ),
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='current_control_number',
            field=models.IntegerField(
                default=0,
                help_text='El último número de control utilizado.',
                verbose_name='Número de Control Actual',
            ),
        ),
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='control_number_length',
            field=models.IntegerField(
                default=5,
                help_text='Número de dígitos para el control (ej: 5 para 00001).',
                verbose_name='Longitud del Número de Control',
            ),
        ),
    ]
