# Generated by Django 5.1 on 2026-09-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_correlativo_numero_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='pais_codigo',
            field=models.CharField(choices=[('VE', 'Venezuela'), ('CO', 'Colombia'), ('PE', 'Perú')], default='VE', help_text='País fiscal del tenant. Determina qué TaxStrategy (apps.configuracion.core.tax_strategy) se aplica por defecto.', max_length=2, verbose_name='País'),
        ),
    ]
