# Generated by Django 5.1.15 on 2026-09-14 12:13

from django.db import migrations, models


def actualizar_prefijo_por_defecto(apps, schema_editor):
    """
    Migra las configuraciones que TODAVÍA tienen el viejo prefijo por defecto
    ("CTRL-", que nunca fue un número de control SENIAT válido) al formato
    real ("00-").

    Solo toca filas que nunca emitieron un número de control
    (``current_control_number == 0``): si el tenant ya facturó con "CTRL-",
    cambiarle el prefijo en caliente rompería la continuidad de su
    numeración fiscal -- ese caso se deja para que el admin lo ajuste a mano
    desde Configuración > Correlativos, con conocimiento de causa.
    """
    ConfiguracionCorrelativo = apps.get_model('configuracion', 'ConfiguracionCorrelativo')
    ConfiguracionCorrelativo.objects.filter(
        prefijo_numero_control='CTRL-', control_number_length=5, current_control_number=0,
    ).update(prefijo_numero_control='00-', control_number_length=8)


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_fase1_pais_y_rol_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncorrelativo',
            name='control_number_length',
            field=models.IntegerField(default=8, help_text='Número de dígitos para el control (ej: 8 para 00000001).', verbose_name='Longitud del Número de Control'),
        ),
        migrations.AlterField(
            model_name='configuracioncorrelativo',
            name='prefijo_numero_control',
            field=models.CharField(default='00-', help_text='Prefijo para el número de control SENIAT (ej: 00- para la sucursal única/matriz).', max_length=10, verbose_name='Prefijo Número de Control'),
        ),
        migrations.RunPython(actualizar_prefijo_por_defecto, migrations.RunPython.noop),
    ]
