# Generated by Django 5.1.15 on 2026-09-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_alter_configuracioncorrelativo_control_number_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='control_number_length_nota_credito',
            field=models.IntegerField(default=8, verbose_name='Longitud del Número de Control (Nota de Crédito)'),
        ),
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='control_number_length_nota_debito',
            field=models.IntegerField(default=8, verbose_name='Longitud del Número de Control (Nota de Débito)'),
        ),
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='current_control_number_nota_credito',
            field=models.IntegerField(default=0, verbose_name='Número de Control Actual (Nota de Crédito)'),
        ),
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='current_control_number_nota_debito',
            field=models.IntegerField(default=0, verbose_name='Número de Control Actual (Nota de Débito)'),
        ),
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='prefijo_numero_control_nota_credito',
            field=models.CharField(default='00-', max_length=10, verbose_name='Prefijo Número de Control (Nota de Crédito)'),
        ),
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='prefijo_numero_control_nota_debito',
            field=models.CharField(default='00-', max_length=10, verbose_name='Prefijo Número de Control (Nota de Débito)'),
        ),
    ]
