# Generated by Django 5.1 on 2026-09-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_configuracioncorrelativo_control_number_length_nota_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='pin_autorizacion_hash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='PIN de autorización (hash)'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='requiere_pin_eliminar',
            field=models.BooleanField(default=False, help_text='Si está activo, eliminar un renglón (ítem del POS, de una mesa, etc.) exige este PIN antes de aplicarse -- para negocios que no dejan al cajero quitar un producto sin autorización.', verbose_name='Exigir PIN para eliminar renglones'),
        ),
    ]
