# Generated by Django 5.1.15 on 2026-09-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_configuracionempresa_pin_autorizacion_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='current_number_nota_entrega',
            field=models.IntegerField(default=0, verbose_name='Número Actual (Nota de Entrega)'),
        ),
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='number_length_nota_entrega',
            field=models.IntegerField(default=3, verbose_name='Longitud del Número (Nota de Entrega)'),
        ),
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='prefijo_nota_entrega',
            field=models.CharField(default='NE-', max_length=10, verbose_name='Prefijo Nota de Entrega'),
        ),
    ]
