# Generated by Django 5.1.15 on 2026-09-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_configuracioncorrelativo_current_number_nota_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='mensaje_whatsapp_venta',
            field=models.TextField(blank=True, default='Hola {cliente}, gracias por tu compra{factura}. Total: {moneda} {total}. ¡Que la disfrutes!', help_text='Variables disponibles: {cliente}, {factura} (correlativo entre paréntesis, o vacío), {total}, {moneda}. El link al PDF de la factura se agrega siempre al final, no se configura aquí.', verbose_name='Mensaje de WhatsApp al cerrar una venta'),
        ),
    ]
