# Generated by Django 5.1 on 2026-10-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0010_configuracionempresa_mensaje_whatsapp_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='current_numero_retencion_islr',
            field=models.IntegerField(default=0, verbose_name='Último secuencial de comprobante de retención ISLR'),
        ),
        migrations.AddField(
            model_name='configuracioncorrelativo',
            name='current_numero_retencion_iva',
            field=models.IntegerField(default=0, verbose_name='Último secuencial de comprobante de retención IVA'),
        ),
    ]
