# Generated by Django 5.1.15 on 2026-09-20 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_alter_nivelprecio_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('contabilizado', 'Contabilizado'), ('anulado', 'Anulado')], default='contabilizado', max_length=15)),
                ('origen', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'db_table': 'AsientoContable',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej. "1.1.01".', max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('costo', 'Costo'), ('gasto', 'Gasto')], max_length=12)),
                ('naturaleza', models.CharField(choices=[('deudora', 'Deudora (Débito)'), ('acreedora', 'Acreedora (Crédito)')], max_length=10)),
                ('acepta_movimiento', models.BooleanField(default=True, help_text='Falso para cuentas "de grupo" (organizan el plan pero no reciben asientos directamente).', verbose_name='Acepta movimiento')),
                ('activo', models.BooleanField(default=True)),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcuentas', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'db_table': 'CuentaContable',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='AsientoContableDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Detalle de Asiento',
                'verbose_name_plural': 'Detalles de Asiento',
                'db_table': 'AsientoContableDetalle',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion_fiscal', models.CharField(blank=True, help_text='RIF/NIT/RUC de la empresa, según el país.', max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente asociado para poder facturarle honorarios profesionales (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_contable', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Empresa Contable',
                'verbose_name_plural': 'Empresas Contables',
                'db_table': 'EmpresaContable',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='contabilidad.empresacontable'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='contabilidad.empresacontable'),
        ),
        migrations.AlterUniqueTogether(
            name='cuentacontable',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='asientocontable',
            unique_together={('empresa', 'numero')},
        ),
    ]
