# Generated by Django 5.1.15 on 2026-09-20 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_contables/'),
        ),
        migrations.AddField(
            model_name='asientocontabledetalle',
            name='conciliado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asientocontabledetalle',
            name='fecha_conciliacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresacontable',
            name='cuenta_cobro_default',
            field=models.ForeignKey(blank=True, help_text='Cuenta a debitar por defecto al cobrar (ej. Caja/Bancos).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='empresacontable',
            name='cuenta_ingreso_default',
            field=models.ForeignKey(blank=True, help_text='Cuenta a acreditar por defecto (ej. Ingresos por Honorarios/Ventas).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='empresacontable',
            name='cuenta_iva_default',
            field=models.ForeignKey(blank=True, help_text='Cuenta de IVA por pagar, para separar el IVA del ingreso en el asiento automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='empresacontable',
            name='es_negocio_propio',
            field=models.BooleanField(default=False, help_text='Si se marca, las ventas normales del sistema (no solo honorarios) pueden generarle asiento automático.', verbose_name='Es el negocio propio del tenant'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('contabilizado', 'Contabilizado'), ('anulado', 'Anulado')], default='contabilizado', max_length=15),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('honorarios', 'Facturación de Honorarios'), ('venta', 'Venta del Sistema'), ('cierre', 'Cierre de Ejercicio')], default='manual', max_length=10),
        ),
        migrations.CreateModel(
            name='AsientoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. "Alquiler mensual", "Nómina quincenal".', max_length=150)),
                ('descripcion_asiento', models.CharField(blank=True, default='', help_text='Descripción que traerá el asiento al usar esta plantilla (se puede editar antes de guardar).', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='contabilidad.empresacontable')),
            ],
            options={
                'verbose_name': 'Plantilla de Asiento',
                'verbose_name_plural': 'Plantillas de Asiento',
                'db_table': 'AsientoPlantilla',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsientoPlantillaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.asientoplantilla')),
            ],
            options={
                'verbose_name': 'Línea de Plantilla',
                'verbose_name_plural': 'Líneas de Plantilla',
                'db_table': 'AsientoPlantillaLinea',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CierreEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cierre_ejercicio', to='contabilidad.asientocontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='contabilidad.empresacontable')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Ejercicio',
                'verbose_name_plural': 'Cierres de Ejercicio',
                'db_table': 'CierreEjercicio',
                'ordering': ['-fecha_hasta'],
            },
        ),
    ]
