# Generated by Django 5.1.15 on 2026-09-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_cuentacontable_rol_alter_asientocontable_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientocontable',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('honorarios', 'Facturación de Honorarios'), ('venta', 'Venta del Sistema'), ('ajuste_inventario', 'Ajuste de Inventario'), ('pago_proveedor', 'Pago a Proveedor'), ('nomina', 'Nómina'), ('cierre', 'Cierre de Ejercicio')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='rol',
            field=models.CharField(blank=True, choices=[('caja', 'Caja'), ('banco', 'Bancos'), ('cuentas_por_cobrar', 'Cuentas por Cobrar'), ('inventario', 'Inventario'), ('iva_por_cobrar', 'IVA Crédito Fiscal (por cobrar)'), ('iva_por_pagar', 'IVA Débito Fiscal (por pagar)'), ('cuentas_por_pagar', 'Cuentas por Pagar Proveedores'), ('ventas', 'Ingresos por Ventas'), ('costo_venta', 'Costo de Ventas'), ('otros_ingresos', 'Otros Ingresos'), ('gasto_sueldos', 'Gasto de Sueldos y Salarios')], help_text='Rol de negocio de esta cuenta (opcional) -- permite que los asientos automáticos (ventas, ajustes de inventario) encuentren la cuenta correcta sin depender de su código.', max_length=20, null=True),
        ),
    ]
