# Generated by Django 5.1 on 2026-05-01 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportecliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_compras', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_pedidos', models.IntegerField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
                ('producto_mas_comprado', models.ForeignKey(blank=True, db_column='producto_mas_comprado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'ReporteCliente',
            },
        ),
        migrations.CreateModel(
            name='Reporteinventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('stock_inicial', models.IntegerField()),
                ('stock_final', models.IntegerField()),
                ('movimientos', models.IntegerField()),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.almacen')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'ReporteInventario',
            },
        ),
        migrations.CreateModel(
            name='Reporteventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_transacciones', models.IntegerField()),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.almacen')),
            ],
            options={
                'db_table': 'ReporteVenta',
            },
        ),
    ]
