# Generated by Django 5.1 on 2026-05-13 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Pago Móvil, Zelle, Efectivo', max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_manual', models.BooleanField(default=False, help_text='Indica si el pago requiere verificación manual.')),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones para el cliente (ej: datos de Pago Móvil).', null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Método de Pago',
                'verbose_name_plural': 'Configuraciones de Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='PagoMovilConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('metodo_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_movil_config', to='pagos.metodopagoconfig')),
            ],
            options={
                'verbose_name': 'Configuración Pago Móvil',
                'verbose_name_plural': 'Configuraciones Pago Móvil',
            },
        ),
        migrations.CreateModel(
            name='TransaccionPasarela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_externa', models.CharField(blank=True, help_text='ID de transacción de la pasarela.', max_length=255, null=True)),
                ('estado', models.CharField(default='pendiente', help_text='Ej: pendiente, completado, fallido, reembolsado.', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.factura')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.metodopagoconfig')),
            ],
            options={
                'verbose_name': 'Transacción de Pasarela',
                'verbose_name_plural': 'Transacciones de Pasarela',
            },
        ),
        migrations.CreateModel(
            name='ZelleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_zelle', models.EmailField(max_length=254)),
                ('nombre_beneficiario', models.CharField(max_length=255)),
                ('metodo_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zelle_config', to='pagos.metodopagoconfig')),
            ],
            options={
                'verbose_name': 'Configuración Zelle',
                'verbose_name_plural': 'Configuraciones Zelle',
            },
        ),
    ]
