# Generated by Django 5.1 on 2026-05-24 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_detallefactura_iva_linea_and_more'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopagoconfig',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='metodopagoconfig',
            name='es_manual',
            field=models.BooleanField(default=False, help_text='Indica si el pago requiere verificación manual.', verbose_name='Verificación Manual'),
        ),
        migrations.AlterField(
            model_name='metodopagoconfig',
            name='instrucciones',
            field=models.TextField(blank=True, help_text='Instrucciones para el cliente (ej: datos de Pago Móvil).', null=True, verbose_name='Instrucciones para el Cliente'),
        ),
        migrations.AlterField(
            model_name='metodopagoconfig',
            name='nombre',
            field=models.CharField(help_text='Ej: Pago Móvil, Zelle, Efectivo', max_length=100, unique=True, verbose_name='Nombre del Método'),
        ),
        migrations.AlterField(
            model_name='pagomovilconfig',
            name='banco',
            field=models.CharField(max_length=100, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='pagomovilconfig',
            name='cedula',
            field=models.CharField(max_length=20, verbose_name='Cédula / RIF'),
        ),
        migrations.AlterField(
            model_name='pagomovilconfig',
            name='metodo_pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_movil_config', to='pagos.metodopagoconfig', verbose_name='Método de Pago Asociado'),
        ),
        migrations.AlterField(
            model_name='pagomovilconfig',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='transaccionpasarela',
            name='estado',
            field=models.CharField(default='pendiente', help_text='Ej: pendiente, completado, fallido, reembolsado.', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='transaccionpasarela',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.factura', verbose_name='Factura Asociada'),
        ),
        migrations.AlterField(
            model_name='transaccionpasarela',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='transaccionpasarela',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='transaccionpasarela',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.metodopagoconfig', verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='transaccionpasarela',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='transaccionpasarela',
            name='referencia_externa',
            field=models.CharField(blank=True, help_text='ID de transacción de la pasarela.', max_length=255, null=True, verbose_name='Referencia Externa'),
        ),
        migrations.AlterField(
            model_name='zelleconfig',
            name='email_zelle',
            field=models.EmailField(max_length=254, verbose_name='Email de Zelle'),
        ),
        migrations.AlterField(
            model_name='zelleconfig',
            name='metodo_pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zelle_config', to='pagos.metodopagoconfig', verbose_name='Método de Pago Asociado'),
        ),
        migrations.AlterField(
            model_name='zelleconfig',
            name='nombre_beneficiario',
            field=models.CharField(max_length=255, verbose_name='Nombre del Beneficiario'),
        ),
    ]
