# Generated by Django 5.1.15 on 2026-09-12 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_metodopagoconfig_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishable_key', models.CharField(help_text='Empieza con pk_test_ o pk_live_.', max_length=255, verbose_name='Publishable Key')),
                ('secret_key', models.CharField(help_text='Empieza con sk_test_ o sk_live_. Nunca se muestra de vuelta una vez guardada.', max_length=255, verbose_name='Secret Key')),
                ('webhook_secret', models.CharField(blank=True, help_text='whsec_... -- para que Stripe confirme pagos automáticamente.', max_length=255, null=True, verbose_name='Webhook Signing Secret')),
                ('moneda', models.CharField(default='usd', help_text='Código ISO 4217 en minúsculas (usd, eur, etc).', max_length=3, verbose_name='Moneda')),
                ('metodo_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_config', to='pagos.metodopagoconfig', verbose_name='Método de Pago Asociado')),
            ],
            options={
                'verbose_name': 'Configuración de Stripe',
                'verbose_name_plural': 'Configuraciones de Stripe',
            },
        ),
    ]
