# nixpacks.toml

[phases.setup]
# AÑADIMOS libffi-dev y el propio libgobject-2.0-0 para estar seguros
aptPkgs = ['libpango-1.0-0', 'libcairo2', 'libgdk-pixbuf-2.0-0', 'libffi-dev', 'libgobject-2.0-0']

[start]
cmd = 'gunicorn backend.wsgi --bind 0.0.0.0:8000'