# Generated by Django 5.1 on 2026-05-13 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('rrhh', '0003_alter_asistencia_options_alter_descanso_options_and_more'),
        ('usuarios', '0002_usermetadata_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logactividad',
            options={'ordering': ['-fecha'], 'verbose_name': 'Log de Actividad', 'verbose_name_plural': 'Logs de Actividad'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol de Usuario', 'verbose_name_plural': 'Roles de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='sesionusuario',
            options={'verbose_name': 'Sesión de Usuario', 'verbose_name_plural': 'Sesiones de Usuarios'},
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='accion',
            field=models.CharField(max_length=100, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='detalles',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usermetadata', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol'),
        ),
        migrations.AlterField(
            model_name='sesionusuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='sesionusuario',
            name='datos',
            field=models.TextField(verbose_name='Datos de Sesión'),
        ),
        migrations.AlterField(
            model_name='sesionusuario',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='sesionusuario',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ID de Sesión'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='almacen_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.almacen', verbose_name='Almacén Asignado'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Notas privadas para administradores sobre el empleado.', null=True, verbose_name='Notas Internas'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='numero_empleado',
            field=models.CharField(blank=True, help_text='Identificador único interno para el empleado', max_length=20, null=True, unique=True, verbose_name='Número de Empleado'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='puesto',
            field=models.CharField(blank=True, help_text='El cargo del empleado (ej: Vendedor, Gerente)', max_length=100, null=True, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.rol', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.sucursal', verbose_name='Sucursal Asignada'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
