# Generated by Django 5.1 on 2026-09-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_loginattempt_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='codigo',
            field=models.CharField(blank=True, help_text="Identificador estable usado por el sistema de permisos (ej: 'admin', 'vendedor').", max_length=30, null=True, unique=True, verbose_name='Código'),
        ),
    ]
