# Generated by Django 5.1.15 on 2026-09-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_backfill_rol_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='modulos_ocultos',
            field=models.JSONField(blank=True, default=list, verbose_name='Módulos ocultos'),
        ),
    ]
