# Generated by Django 5.1.15 on 2026-09-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usermetadata_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='sueldo_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto a pagar por período de nómina. Vacío = no participa en nómina.', max_digits=12, null=True, verbose_name='Sueldo Base'),
        ),
    ]
