# Generated by Django 5.1 on 2025-04-02 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Almacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                "db_table": "Almacen",
            },
        ),
        migrations.CreateModel(
            name="Atributoproducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "AtributoProducto",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_documento", models.CharField(max_length=10)),
                ("documento", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=254, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                (
                    "codigo_postal",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("provincia", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_registro", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Cliente",
            },
        ),
        migrations.CreateModel(
            name="Configuracioniva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("porcentaje_iva", models.DecimalField(decimal_places=2, max_digits=5)),
                ("activo", models.BooleanField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ConfiguracionIVA",
            },
        ),
        migrations.CreateModel(
            name="Pedidoproveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pedido", models.DateField(blank=True, null=True)),
                ("fecha_esperada", models.DateField()),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "PedidoProveedor",
            },
        ),
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("tipo", models.CharField(max_length=20)),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("max_usos", models.IntegerField(blank=True, null=True)),
                ("usos_actuales", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "Promocion",
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cif", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.CharField(max_length=254)),
                ("plazo_pago", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "Proveedor",
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Rol",
            },
        ),
        migrations.CreateModel(
            name="Sesionusuario",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("datos", models.TextField()),
                ("fecha_actualizacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "SesionUsuario",
            },
        ),
        migrations.CreateModel(
            name="Tipodocumentofiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("descripcion", models.CharField(max_length=100)),
                ("obligatorio", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "TipoDocumentoFiscal",
            },
        ),
        migrations.CreateModel(
            name="Transportista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("tipo_envio", models.CharField(max_length=50)),
                ("precio_base", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_kg_adicional",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("tiempo_entrega", models.CharField(max_length=20)),
                ("activo", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "Transportista",
            },
        ),
        migrations.CreateModel(
            name="Categoriaproducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("slug", models.CharField(max_length=100, unique=True)),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.categoriaproducto",
                    ),
                ),
            ],
            options={
                "db_table": "CategoriaProducto",
            },
        ),
        migrations.CreateModel(
            name="Cupondescuento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("tipo", models.CharField(max_length=15)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valido_desde", models.DateField()),
                ("valido_hasta", models.DateField()),
                ("usos_maximos", models.IntegerField(blank=True, null=True)),
                ("usos_actuales", models.IntegerField(blank=True, null=True)),
                (
                    "minimo_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "solo_almacen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.almacen",
                    ),
                ),
                (
                    "solo_categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.categoriaproducto",
                    ),
                ),
            ],
            options={
                "db_table": "CuponDescuento",
            },
        ),
        migrations.CreateModel(
            name="Direccionenvio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=50)),
                ("direccion", models.TextField()),
                ("codigo_postal", models.CharField(max_length=5)),
                ("provincia", models.CharField(max_length=50)),
                ("telefono_contacto", models.CharField(max_length=15)),
                ("predeterminada", models.BooleanField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "DireccionEnvio",
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_emision", models.DateTimeField(blank=True, null=True)),
                ("fecha_operacion", models.DateTimeField()),
                ("correlativo", models.CharField(max_length=50, unique=True)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "descuento_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "base_imponible",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("iva_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
                ("metodo_pago", models.CharField(max_length=50)),
                ("nif_factura", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "almacen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.almacen",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "Factura",
            },
        ),
        migrations.CreateModel(
            name="Facturaelectronica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv", models.CharField(max_length=50)),
                ("qr_code", models.BinaryField()),
                ("firma_electronica", models.TextField()),
                ("fecha_registro_aeat", models.DateTimeField()),
                (
                    "factura",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.factura",
                    ),
                ),
            ],
            options={
                "db_table": "FacturaElectronica",
            },
        ),
        migrations.CreateModel(
            name="Lecturacodigobarras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_barras", models.CharField(max_length=50)),
                ("fecha_lectura", models.DateTimeField(blank=True, null=True)),
                (
                    "almacen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.almacen",
                    ),
                ),
            ],
            options={
                "db_table": "LecturaCodigoBarras",
            },
        ),
        migrations.CreateModel(
            name="Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(max_length=20)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("direccion_envio", models.TextField()),
                ("metodo_pago", models.CharField(max_length=50)),
                (
                    "transaccion_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "Orden",
            },
        ),
        migrations.AddField(
            model_name="factura",
            name="orden",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="erp.orden",
            ),
        ),
        migrations.CreateModel(
            name="Envio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion", models.TextField()),
                (
                    "transportista",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "numero_seguimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "costo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                (
                    "almacen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.almacen",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.orden",
                    ),
                ),
            ],
            options={
                "db_table": "Envio",
            },
        ),
        migrations.CreateModel(
            name="Devolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.TextField()),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "monto_reembolso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(blank=True, null=True)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "orden",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.orden",
                    ),
                ),
            ],
            options={
                "db_table": "Devolucion",
            },
        ),
        migrations.CreateModel(
            name="Contabilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_asiento", models.CharField(max_length=20)),
                ("fecha", models.DateField()),
                ("concepto", models.TextField()),
                ("debe", models.DecimalField(decimal_places=2, max_digits=10)),
                ("haber", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "factura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.factura",
                    ),
                ),
                (
                    "pedido_proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.pedidoproveedor",
                    ),
                ),
            ],
            options={
                "db_table": "Contabilidad",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("codigo_barras", models.CharField(max_length=50, unique=True)),
                ("disponible_online", models.BooleanField(blank=True, null=True)),
                (
                    "descuento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("dimensiones", models.CharField(blank=True, max_length=50, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "configuracion_iva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.configuracioniva",
                    ),
                ),
            ],
            options={
                "db_table": "Producto",
            },
        ),
        migrations.CreateModel(
            name="Detallefactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "subtotal_linea",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("iva_linea", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_linea", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "factura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.factura",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.producto",
                    ),
                ),
            ],
            options={
                "db_table": "DetalleFactura",
            },
        ),
        migrations.AddField(
            model_name="pedidoproveedor",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="erp.proveedor",
            ),
        ),
        migrations.CreateModel(
            name="Reportecliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_compras", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cantidad_pedidos", models.IntegerField()),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.cliente",
                    ),
                ),
                (
                    "producto_mas_comprado",
                    models.ForeignKey(
                        blank=True,
                        db_column="producto_mas_comprado",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.producto",
                    ),
                ),
            ],
            options={
                "db_table": "ReporteCliente",
            },
        ),
        migrations.CreateModel(
            name="Reporteinventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("stock_inicial", models.IntegerField()),
                ("stock_final", models.IntegerField()),
                ("movimientos", models.IntegerField()),
                (
                    "almacen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.almacen",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.producto",
                    ),
                ),
            ],
            options={
                "db_table": "ReporteInventario",
            },
        ),
        migrations.CreateModel(
            name="Reporteventa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("total_ventas", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_iva", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_descuentos",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("cantidad_transacciones", models.IntegerField()),
                (
                    "almacen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.almacen",
                    ),
                ),
            ],
            options={
                "db_table": "ReporteVenta",
            },
        ),
        migrations.CreateModel(
            name="Reservastock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("valido_hasta", models.DateTimeField()),
                ("fecha_creacion", models.DateTimeField(blank=True, null=True)),
                (
                    "almacen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.almacen",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.orden",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.producto",
                    ),
                ),
            ],
            options={
                "db_table": "ReservaStock",
            },
        ),
        migrations.CreateModel(
            name="Transaccionpago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("metodo_pago", models.CharField(max_length=50)),
                ("estado", models.CharField(max_length=20)),
                (
                    "codigo_transaccion",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("fecha", models.DateTimeField(blank=True, null=True)),
                (
                    "orden",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.orden",
                    ),
                ),
            ],
            options={
                "db_table": "TransaccionPago",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("ultimo_login", models.DateTimeField(blank=True, null=True)),
                ("avatar_url", models.CharField(blank=True, max_length=255, null=True)),
                ("provider", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "rol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.rol",
                    ),
                ),
            ],
            options={
                "db_table": "Usuario",
            },
        ),
        migrations.CreateModel(
            name="Resenaproducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calificacion", models.IntegerField()),
                ("comentario", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(blank=True, null=True)),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "ResenaProducto",
            },
        ),
        migrations.AddField(
            model_name="orden",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="erp.usuario",
            ),
        ),
        migrations.CreateModel(
            name="Logactividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=100)),
                ("detalles", models.TextField(blank=True, null=True)),
                ("fecha", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "LogActividad",
            },
        ),
        migrations.CreateModel(
            name="Consentimientousuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_consentimiento", models.CharField(max_length=50)),
                ("version", models.TextField()),
                ("fecha_aceptacion", models.DateTimeField(blank=True, null=True)),
                ("ip_aceptacion", models.GenericIPAddressField()),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "ConsentimientoUsuario",
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="erp.usuario",
            ),
        ),
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(blank=True, null=True)),
                ("fecha_actualizacion", models.DateTimeField(blank=True, null=True)),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "Carrito",
            },
        ),
        migrations.CreateModel(
            name="Variacionproducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.CharField(max_length=100)),
                (
                    "sku",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("stock", models.IntegerField(blank=True, null=True)),
                (
                    "atributo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.atributoproducto",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.producto",
                    ),
                ),
            ],
            options={
                "db_table": "VariacionProducto",
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(blank=True, null=True)),
                ("stock_minimo", models.IntegerField(blank=True, null=True)),
                ("stock_reservado", models.IntegerField(blank=True, null=True)),
                (
                    "almacen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.almacen",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.producto",
                    ),
                ),
            ],
            options={
                "db_table": "Inventario",
                "unique_together": {("producto", "almacen")},
            },
        ),
        migrations.CreateModel(
            name="Productocategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.categoriaproducto",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.producto",
                    ),
                ),
            ],
            options={
                "db_table": "ProductoCategoria",
                "unique_together": {("producto", "categoria")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="cliente",
            unique_together={("tipo_documento", "documento")},
        ),
    ]
