# Generated by Django 5.1 on 2025-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
