# Generated by Django 5.1 on 2025-04-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_cliente_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriaproducto",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
