# Generated by Django 5.1 on 2025-04-02 19:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_categoriaproducto_activo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaproducto",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="nombre"),
        ),
    ]
