# Generated by Django 5.1 on 2025-04-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0004_alter_categoriaproducto_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="almacen",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
