# Generated by Django 5.1 on 2025-04-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0005_almacen_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventario",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
