# Generated by Django 5.1 on 2025-04-04 19:48

import django.db.models.deletion
import erp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0006_inventario_activo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="inventario",
            name="stock_reservado",
        ),
        migrations.AddField(
            model_name="producto",
            name="almacen",
            field=models.ForeignKey(
                default=None, on_delete=erp.models.Almacen, to="erp.almacen"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inventario",
            name="almacen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp.almacen",
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp.producto",
            ),
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("salida", "Salida")],
                        max_length=10,
                    ),
                ),
                ("fecha_movimiento", models.DateTimeField(auto_now_add=True)),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erp.inventario"
                    ),
                ),
            ],
            options={
                "db_table": "MovimientoInventario",
            },
        ),
    ]
