# Generated by Django 5.1 on 2025-04-04 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0007_remove_inventario_cantidad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="cantidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp.producto",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="cantidad",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
