# Generated by Django 5.1 on 2025-04-04 19:51

import erp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0008_movimientoinventario_cantidad_producto_cantidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="almacen",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=erp.models.Almacen, to="erp.almacen"
            ),
        ),
    ]
