# Generated by Django 5.1 on 2025-04-04 19:51

import erp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0009_alter_producto_almacen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="almacen",
            field=models.ForeignKey(
                default=1, on_delete=erp.models.Almacen, to="erp.almacen"
            ),
        ),
    ]
