# Generated by Django 5.1 on 2025-04-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0011_alter_producto_almacen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movimientoinventario",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="cantidad",
        ),
    ]
