# Generated by Django 5.1 on 2025-04-04 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0012_remove_movimientoinventario_cantidad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="cantidad",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="almacen",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp.almacen",
            ),
        ),
    ]
