# Generated by Django 5.1 on 2025-04-04 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0013_producto_cantidad_alter_producto_almacen"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="cantidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp.producto",
            ),
        ),
    ]
