# Generated by Django 5.1 on 2025-04-07 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0014_movimientoinventario_cantidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp.categoriaproducto",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="almacen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp.almacen",
            ),
        ),
    ]
