# Generated by Django 5.1 on 2025-04-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0015_producto_categoria_alter_producto_almacen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="stock_minimo",
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="stock_minimo",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
