# Generated by Django 5.1 on 2025-04-09 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0016_remove_inventario_stock_minimo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=100, null=True)),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("ultimo_login", models.DateTimeField(blank=True, null=True)),
                ("avatar_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "rol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.rol",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "UserMetadata",
            },
        ),
        migrations.AlterField(
            model_name="carrito",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="erp.usermetadata",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="erp.usermetadata",
            ),
        ),
        migrations.AlterField(
            model_name="consentimientousuario",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="erp.usermetadata",
            ),
        ),
        migrations.AlterField(
            model_name="logactividad",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="erp.usermetadata",
            ),
        ),
        migrations.AlterField(
            model_name="orden",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="erp.usermetadata",
            ),
        ),
        migrations.AlterField(
            model_name="resenaproducto",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="erp.usermetadata",
            ),
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
