# Generated by Django 5.1 on 2025-04-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0017_usermetadata_alter_carrito_usuario_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermetadata",
            name="token",
        ),
        migrations.AddField(
            model_name="devolucion",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="factura",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="orden",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="rol",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sesionusuario",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tipodocumentofiscal",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="transaccionpago",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="configuracioniva",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
