# Generated by Django 5.1 on 2025-04-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0018_remove_usermetadata_token_devolucion_activo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventario",
            name="cantidad",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orden",
            name="correlativo",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="orden",
            name="descuento_producto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orden",
            name="descuento_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orden",
            name="fecha_operacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orden",
            name="iva_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orden",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orden",
            name="direccion_envio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orden",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="orden",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
