# Generated by Django 5.1 on 2025-04-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0019_inventario_cantidad_orden_correlativo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionCorrelativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefijo", models.CharField(default="F-", max_length=10)),
                ("current_number", models.IntegerField(default=0)),
                ("number_length", models.IntegerField(default=3)),
            ],
            options={
                "db_table": "ConfiguracionCorrelativo",
            },
        ),
    ]
