# Generated by Django 5.1 on 2025-04-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0020_configuracioncorrelativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="almacen",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AND", "Andalucía"),
                    ("ARA", "Aragón"),
                    ("AST", "Asturias"),
                    ("BAL", "Baleares"),
                    ("CAN", "Canarias"),
                    ("CANT", "Cantabria"),
                    ("CLM", "Castilla-La Mancha"),
                    ("CYL", "Castilla y León"),
                    ("CAT", "Cataluña"),
                    ("EXT", "Extremadura"),
                    ("GAL", "Galicia"),
                    ("RIA", "La Rioja"),
                    ("MAD", "Madrid"),
                    ("MUR", "Murcia"),
                    ("NAV", "Navarra"),
                    ("PV", "País Vasco"),
                    ("VAL", "Valencia"),
                ],
                default="CYL",
                max_length=4,
                null=True,
            ),
        ),
    ]
