# Generated by Django 5.1 on 2025-05-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0021_almacen_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variacionproducto",
            name="atributo",
        ),
        migrations.AddField(
            model_name="variacionproducto",
            name="nombre",
            field=models.CharField(default="", max_length=80),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Atributoproducto",
        ),
    ]
