# Generated by Django 5.1 on 2025-05-05 18:03

import erp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0022_remove_variacionproducto_atributo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
        migrations.AddField(
            model_name="variacionproducto",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to=erp.models.variant_image_upload_to
            ),
        ),
    ]
