# Generated by Django 5.1 on 2025-05-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0023_producto_imagen_variacionproducto_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracioniva",
            name="activo",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
