# Generated by Django 5.1 on 2025-05-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0024_alter_configuracioniva_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioniva",
            name="nombre",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
