# Generated by Django 5.1 on 2025-05-10 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0026_alter_producto_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "MetodoPago",
            },
        ),
        migrations.AlterField(
            model_name="factura",
            name="metodo_pago",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="erp.metodopago",
            ),
        ),
        migrations.AlterField(
            model_name="orden",
            name="metodo_pago",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="erp.metodopago",
            ),
        ),
        migrations.AlterField(
            model_name="transaccionpago",
            name="metodo_pago",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="erp.metodopago",
            ),
        ),
    ]
