# Generated by Django 5.1 on 2025-05-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0027_metodopago_alter_factura_metodo_pago_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metodopago",
            name="nro_cuenta",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="metodopago",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="metodopago",
            name="tipo_metodo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
