# Generated by Django 5.1 on 2025-05-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0028_metodopago_nro_cuenta_metodopago_telefono_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="factura",
            old_name="metodo_pago",
            new_name="metodoPago",
        ),
        migrations.RenameField(
            model_name="orden",
            old_name="metodo_pago",
            new_name="metodoPago",
        ),
        migrations.RenameField(
            model_name="transaccionpago",
            old_name="metodo_pago",
            new_name="metodoPago",
        ),
    ]
