# Generated by Django 5.1 on 2025-05-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0029_rename_metodo_pago_factura_metodopago_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="factura",
            old_name="metodoPago",
            new_name="metodo_pago",
        ),
        migrations.RenameField(
            model_name="orden",
            old_name="metodoPago",
            new_name="metodo_pago",
        ),
        migrations.RenameField(
            model_name="transaccionpago",
            old_name="metodoPago",
            new_name="metodo_pago",
        ),
    ]
