# Generated by Django 5.1 on 2025-05-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0030_rename_metodopago_factura_metodo_pago_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="factura",
            old_name="descuento_total",
            new_name="descuento",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="base_imponible",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="fecha_emision",
        ),
    ]
