# Generated by Django 5.1 on 2025-05-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0031_rename_descuento_total_factura_descuento_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="factura",
            old_name="descuento",
            new_name="descuento_global",
        ),
    ]
