# Generated by Django 5.1 on 2025-05-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0032_rename_descuento_factura_descuento_global"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="comentario_pendiente",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="factura",
            name="nombre_cliente_pendiente",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
