# Generated by Django 5.1 on 2025-05-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0033_factura_comentario_pendiente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="correlativo",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
