# Generated by Django 5.1 on 2025-05-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0034_alter_factura_correlativo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variacionproducto",
            old_name="stock",
            new_name="cantidad",
        ),
        migrations.AddField(
            model_name="variacionproducto",
            name="atributo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="variacionproducto",
            name="codigo_barras",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="variacionproducto",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
