# Generated by Django 5.1 on 2025-05-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0035_rename_stock_variacionproducto_cantidad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="tipo",
            field=models.CharField(
                choices=[("simple", "Simple"), ("variable", "Variable")],
                default="simple",
                max_length=20,
            ),
        ),
    ]
