# Generated by Django 5.1 on 2025-05-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0036_producto_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
