# Generated by Django 5.1 on 2025-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0037_alter_producto_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="codigo_barras",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
