# Generated by Django 5.1 on 2025-05-27 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0038_alter_producto_codigo_barras"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atributo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name="variacionproducto",
            name="atributo",
        ),
        migrations.RemoveField(
            model_name="variacionproducto",
            name="valor",
        ),
        migrations.CreateModel(
            name="ValorAtributo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.CharField(max_length=80)),
                (
                    "atributo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erp.atributo"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="variacionproducto",
            name="atributos",
            field=models.ManyToManyField(to="erp.valoratributo"),
        ),
    ]
