# Generated by Django 5.1 on 2025-06-01 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0039_atributo_remove_variacionproducto_atributo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usermetadata",
            name="apellido",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AddField(
            model_name="usermetadata",
            name="correo",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="usermetadata",
            name="es_activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usermetadata",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="usermetadata",
            name="fecha_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="usermetadata",
            name="nombre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usermetadata",
            name="numero_documento",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="usermetadata",
            name="tipo_documento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp.tipodocumentofiscal",
            ),
        ),
        migrations.AddField(
            model_name="usermetadata",
            name="token_verificacion",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="usermetadata",
            name="verificado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usermetadata",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
