# Generated by Django 5.1 on 2025-06-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0040_usermetadata_apellido_usermetadata_correo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermetadata",
            name="avatar_url",
        ),
    ]
