# Generated by Django 5.1 on 2025-06-16 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0041_remove_usermetadata_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallefactura",
            name="variante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="erp.variacionproducto",
            ),
        ),
    ]
