# Generated by Django 5.1 on 2025-06-18 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0042_detallefactura_variante"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas_creadas",
                to="erp.usermetadata",
            ),
        ),
    ]
