# Generated by Django 5.1 on 2025-07-11 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0043_factura_creado_por"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factura",
            name="creado_por",
        ),
        migrations.AddField(
            model_name="factura",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
