# Generated by Django 5.1 on 2025-07-25 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_categoriaproducto_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoratributo',
            name='atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='erp.atributo'),
        ),
    ]
