# Generated by Django 5.1 on 2025-07-26 00:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0046_alter_valoratributo_atributo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermetadata',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='es_activo',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='token_verificacion',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='ultimo_login',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='verificado',
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='almacen_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.almacen'),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Notas privadas para administradores sobre el empleado.', null=True),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='numero_empleado',
            field=models.CharField(blank=True, help_text='Identificador único interno para el empleado', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='puesto',
            field=models.CharField(blank=True, help_text='El cargo del empleado (ej: Vendedor, Gerente)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 26, 0, 41, 0, 740477, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.rol'),
        ),
    ]
