# Generated by Django 5.1 on 2025-07-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0048_asistencia_descanso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaFestivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Horario General', max_length=100)),
                ('hora_entrada_oficial', models.TimeField()),
                ('hora_salida_oficial', models.TimeField()),
                ('margen_tardanza_minutos', models.PositiveIntegerField(default=5, help_text='Minutos de tolerancia para llegar tarde')),
            ],
        ),
        migrations.AddField(
            model_name='asistencia',
            name='llegada_tarde',
            field=models.BooleanField(default=False),
        ),
    ]
