# Generated by Django 5.1 on 2025-07-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0050_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
