# Generated by Django 5.1 on 2025-07-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0051_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Código único de producto (SKU), usado para sincronizar con otras plataformas.', max_length=100, null=True, unique=True),
        ),
    ]
