# Generated by Django 5.1 on 2025-08-28 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0052_producto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='erp.factura'),
        ),
    ]
