# Generated by Django 5.1.15 on 2026-09-20 17:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_alter_nivelprecio_options_and_more'),
        ('facturacion', '0016_factura_pendiente_de_aprobacion'),
        ('inventario', '0011_alter_ajusteinventariodetalle_costo_unitario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número/Nombre')),
                ('capacidad', models.PositiveIntegerField(blank=True, help_text='Cantidad de comensales que caben.', null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Mesa',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='PedidoMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('token_publico', models.CharField(editable=False, max_length=64, unique=True)),
                ('division_personas', models.PositiveIntegerField(default=1)),
                ('propina_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('mesero_solicitado', models.BooleanField(default=False, help_text='Alguien tocó "Llamar al mesero" desde el QR.')),
                ('cuenta_solicitada', models.BooleanField(default=False, help_text='Alguien tocó "Pedir la cuenta" desde el QR.')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('factura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_mesa', to='facturacion.factura')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='restaurantes.mesa')),
                ('mesero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_mesa_atendidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PedidoMesa',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='PedidoMesaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.CharField(blank=True, help_text='Ej. "sin cebolla", "término medio".', max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurantes.pedidomesa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'db_table': 'PedidoMesaItem',
                'ordering': ['creado'],
            },
        ),
    ]
