# Generated by Django 5.1.15 on 2026-09-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomesa',
            name='datos_pago_anfitrion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
