# Generated by Django 5.1 on 2026-09-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='es_contribuyente_especial',
            field=models.BooleanField(default=False, help_text='Contribuyente Especial designado por el SENIAT -- aplica un porcentaje de retención de IVA distinto al de un contribuyente ordinario.'),
        ),
    ]
