# Generated by Django 5.1 on 2026-10-02 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_alter_asientocontable_origen_and_more'),
        ('inventario', '0022_alter_ajusteinventario_motivo'),
        ('proveedores', '0004_ordencompra_ordencompradetalle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura fiscal'), ('nota_entrega', 'Nota de entrega (sin factura)')], default='factura', max_length=15)),
                ('numero_factura', models.CharField(help_text='Número de la factura (o de la nota de entrega) del proveedor.', max_length=50)),
                ('numero_control', models.CharField(blank=True, default='', help_text='Número de control SENIAT impreso en la factura del proveedor.', max_length=50)),
                ('fecha_emision', models.DateField(help_text='Fecha impresa en el documento del proveedor.')),
                ('monto_exento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retencion_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retencion_islr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('anulada', 'Anulada')], default='registrada', max_length=12)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('ajuste', models.ForeignKey(blank=True, help_text='Entrada de inventario generada por esta compra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_compra', to='inventario.ajusteinventario')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.almacen')),
                ('asiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.asientocontable')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='proveedores.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_compra', to='proveedores.proveedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura de Compra',
                'verbose_name_plural': 'Facturas de Compra',
                'db_table': 'FacturaCompra',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='factura_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_por_pagar', to='proveedores.facturacompra'),
        ),
        migrations.CreateModel(
            name='FacturaCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=6, max_digits=14)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proveedores.facturacompra')),
                ('orden_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='proveedores.ordencompradetalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.variacionproducto')),
            ],
            options={
                'db_table': 'FacturaCompraDetalle',
            },
        ),
        migrations.AddConstraint(
            model_name='facturacompra',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'registrada')), fields=('proveedor', 'tipo_documento', 'numero_factura'), name='uniq_factura_compra_proveedor_numero'),
        ),
    ]
