# Generated by Django 5.1 on 2026-10-03 00:23

import apps.inmuebles.models
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_cliente_contribuyente_especial_cliente_dias_credito_and_more'),
        ('proveedores', '0005_facturacompra_cuentaporpagar_factura_compra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField(blank=True, default='')),
                ('rif', models.CharField(blank=True, default='', max_length=20)),
                ('dia_vencimiento', models.PositiveSmallIntegerField(default=5, help_text='Día del mes en que vencen las cuotas (por defecto al emitir un período).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('mora_pct_mensual', models.DecimalField(decimal_places=2, default=0, help_text='% mensual de mora sobre el saldo vencido (0 = no cobra mora).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('dias_gracia', models.PositiveSmallIntegerField(default=0, help_text='Días después del vencimiento antes de aplicar mora.')),
                ('fondo_reserva_pct', models.DecimalField(decimal_places=2, default=0, help_text='% que se suma a los gastos comunes como fondo de reserva.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('portal_muestra_morosidad', models.BooleanField(default=False, help_text='Si está activo, el portal de cada condómino muestra el resumen de morosidad del edificio (solo códigos de unidad, sin nombres).')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('vigente', 'Vigente'), ('vencido', 'Vencido'), ('rescindido', 'Rescindido')], default='borrador', max_length=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('canon_usd', apps.inmuebles.models.Monto(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('dia_pago', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('deposito_usd', apps.inmuebles.models.Monto(decimal_places=2, default=0, max_digits=14)),
                ('honorario_pct', models.DecimalField(decimal_places=2, default=0, help_text='% que cobra la administradora sobre el canon cobrado.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ajuste_anual_pct', models.DecimalField(decimal_places=2, default=0, help_text='Aumento del canon cada año de contrato.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mora_pct_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('dias_gracia', models.PositiveSmallIntegerField(default=0)),
                ('documento', models.FileField(blank=True, null=True, upload_to=apps.inmuebles.models.ruta_contratos)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_rescision', models.DateField(blank=True, null=True)),
                ('motivo_rescision', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contrato_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='inmuebles.contrato')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_inquilino', to='clientes.cliente')),
                ('propietario', models.ForeignKey(blank=True, help_text='Se copia de la unidad al crear el contrato.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_propietario', to='clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GastoComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Mes al que se carga el gasto (AAAA-MM).', max_length=7, validators=[apps.inmuebles.models.validar_periodo])),
                ('categoria', models.CharField(choices=[('agua', 'Agua'), ('electricidad', 'Electricidad áreas comunes'), ('aseo', 'Aseo y limpieza'), ('vigilancia', 'Vigilancia'), ('mantenimiento', 'Mantenimiento y reparaciones'), ('ascensor', 'Ascensor'), ('jardineria', 'Jardinería'), ('administracion', 'Administración'), ('seguros', 'Seguros'), ('legales', 'Honorarios legales'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_usd', apps.inmuebles.models.Monto(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField()),
                ('comprobante', models.FileField(blank=True, null=True, upload_to=apps.inmuebles.models.ruta_gastos)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='inmuebles.edificio')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='proveedores.proveedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-periodo', '-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Mes en que se emite la liquidación.', max_length=7, validators=[apps.inmuebles.models.validar_periodo])),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=10)),
                ('total_cobrado_usd', apps.inmuebles.models.Monto(decimal_places=2, default=0, max_digits=14)),
                ('honorario_usd', apps.inmuebles.models.Monto(decimal_places=2, default=0, max_digits=14)),
                ('gastos_usd', apps.inmuebles.models.Monto(decimal_places=2, default=0, max_digits=14)),
                ('neto_usd', apps.inmuebles.models.Monto(decimal_places=2, default=0, max_digits=14)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('referencia_pago', models.CharField(blank=True, default='', max_length=100)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-periodo', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('pago_movil', 'Pago móvil'), ('zelle', 'Zelle'), ('efectivo', 'Efectivo'), ('deposito', 'Depósito'), ('otro', 'Otro')], max_length=15)),
                ('titular', models.CharField(blank=True, default='', max_length=150)),
                ('documento_titular', models.CharField(blank=True, default='', help_text='RIF o cédula del titular.', max_length=30)),
                ('banco', models.CharField(blank=True, default='', max_length=100)),
                ('numero_cuenta', models.CharField(blank=True, default='', help_text='Cuenta, teléfono o correo según el tipo.', max_length=40)),
                ('moneda', models.CharField(default='VES', max_length=3)),
                ('instrucciones', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('edificio', models.ForeignKey(blank=True, help_text='Vacío = aplica a todas las unidades (cuenta de la administradora).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='inmuebles.edificio')),
            ],
            options={
                'ordering': ['edificio__nombre', 'tipo', 'banco'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoCondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7, validators=[apps.inmuebles.models.validar_periodo])),
                ('estado', models.CharField(choices=[('emitido', 'Emitido'), ('anulado', 'Anulado')], default='emitido', max_length=10)),
                ('total_gastos_usd', apps.inmuebles.models.Monto(decimal_places=2, max_digits=14)),
                ('fondo_reserva_usd', apps.inmuebles.models.Monto(decimal_places=2, default=0, max_digits=14)),
                ('total_distribuido_usd', apps.inmuebles.models.Monto(decimal_places=2, max_digits=14)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos', to='inmuebles.edificio')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-periodo', 'edificio__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cuota_condominio', 'Cuota de condominio'), ('canon', 'Canon de alquiler'), ('extraordinaria', 'Cuota extraordinaria'), ('multa', 'Multa'), ('mora', 'Mora'), ('deposito', 'Depósito en garantía'), ('otro', 'Otro')], max_length=20)),
                ('concepto', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=7, validators=[apps.inmuebles.models.validar_periodo])),
                ('monto_usd', apps.inmuebles.models.Monto(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monto_fondo_usd', apps.inmuebles.models.Monto(decimal_places=2, default=0, help_text='Parte de la cuota que corresponde al fondo de reserva (informativo).', max_digits=14)),
                ('monto_pagado_usd', apps.inmuebles.models.Monto(decimal_places=2, default=0, max_digits=14)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cargo_origen', models.ForeignKey(blank=True, help_text='Para una mora: la deuda que la originó.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moras', to='inmuebles.cargo')),
                ('pagador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='clientes.cliente')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='inmuebles.contrato')),
                ('periodo_condominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='inmuebles.periodocondominio')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortalAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_portal', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('pago_movil', 'Pago móvil'), ('zelle', 'Zelle'), ('efectivo', 'Efectivo'), ('deposito', 'Depósito'), ('otro', 'Otro')], default='transferencia', max_length=15)),
                ('referencia', models.CharField(blank=True, default='', max_length=100)),
                ('banco', models.CharField(blank=True, default='', max_length=100)),
                ('moneda_pago', models.CharField(default='USD', max_length=3)),
                ('monto_pago', models.DecimalField(decimal_places=2, help_text='Monto recibido, en la moneda en que se pagó.', max_digits=16)),
                ('tasa', models.DecimalField(decimal_places=6, default=1, help_text='Unidades de moneda base por 1 USD al momento del pago.', max_digits=16)),
                ('monto_usd', apps.inmuebles.models.Monto(decimal_places=2, max_digits=14)),
                ('monto_disponible_usd', apps.inmuebles.models.Monto(decimal_places=2, default=0, help_text='Parte del pago que no se aplicó a ninguna deuda (saldo a favor).', max_digits=14)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to=apps.inmuebles.models.ruta_comprobantes)),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('anulado', 'Anulado')], default='confirmado', max_length=12)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, default='', max_length=255)),
                ('pagador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos', to='clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReciboAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_usd', apps.inmuebles.models.Monto(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='inmuebles.cargo')),
                ('liquidacion', models.ForeignKey(blank=True, help_text='Liquidación al propietario en la que ya se incluyó este cobro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones', to='inmuebles.liquidacion')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='inmuebles.recibo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej. "Apto 3-B", "Casa 12", "Local 4".', max_length=40)),
                ('tipo', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('townhouse', 'Townhouse'), ('local', 'Local comercial'), ('oficina', 'Oficina'), ('galpon', 'Galpón'), ('terreno', 'Terreno'), ('estacionamiento', 'Estacionamiento'), ('deposito', 'Depósito'), ('otro', 'Otro')], default='apartamento', max_length=20)),
                ('estado', models.CharField(choices=[('ocupada', 'Ocupada'), ('disponible', 'Disponible'), ('mantenimiento', 'En mantenimiento')], default='ocupada', max_length=15)),
                ('alicuota', models.DecimalField(decimal_places=4, default=0, help_text='% de participación en los gastos comunes (las de un edificio deben sumar 100).', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('operacion', models.CharField(choices=[('ninguna', 'No se ofrece'), ('alquiler', 'Alquiler'), ('venta', 'Venta'), ('alquiler_venta', 'Alquiler o venta')], default='ninguna', max_length=15)),
                ('publicada', models.BooleanField(default=False, help_text='Aparece en el portal público de propiedades.')),
                ('titulo', models.CharField(blank=True, default='', max_length=160)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('zona', models.CharField(blank=True, default='', help_text='Urbanización, sector o zona.', max_length=120)),
                ('ciudad', models.CharField(blank=True, default='', max_length=80)),
                ('precio_venta_usd', apps.inmuebles.models.Monto(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('canon_usd', apps.inmuebles.models.Monto(blank=True, decimal_places=2, help_text='Canon de alquiler mensual sugerido.', max_digits=14, null=True)),
                ('habitaciones', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('banos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estacionamientos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area_construida_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('amenidades', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='inmuebles.edificio')),
                ('ocupante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_ocupadas', to='clientes.cliente')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_propias', to='clientes.cliente')),
            ],
            options={
                'ordering': ['edificio__nombre', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='recibo',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='inmuebles.unidad'),
        ),
        migrations.CreateModel(
            name='PagoReportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('pago_movil', 'Pago móvil'), ('zelle', 'Zelle'), ('efectivo', 'Efectivo'), ('deposito', 'Depósito'), ('otro', 'Otro')], default='transferencia', max_length=15)),
                ('fecha_pago', models.DateField()),
                ('referencia', models.CharField(blank=True, default='', max_length=100)),
                ('banco', models.CharField(blank=True, default='', max_length=100)),
                ('moneda_pago', models.CharField(default='VES', max_length=3)),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=16)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to=apps.inmuebles.models.ruta_comprobantes)),
                ('nota', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('motivo_rechazo', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cargos', models.ManyToManyField(blank=True, help_text='Deudas que dice pagar (vacío = las más antiguas).', related_name='pagos_reportados', to='inmuebles.cargo')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_reportados', to='clientes.cliente')),
                ('medio_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inmuebles.mediopago')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recibo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_reportado', to='inmuebles.recibo')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_reportados', to='inmuebles.unidad')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('canon', 'Canon cobrado'), ('honorario', 'Honorario de administración'), ('gasto', 'Gasto de la propiedad')], max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_usd', apps.inmuebles.models.Monto(decimal_places=2, help_text='Con signo: el canon suma, el honorario y los gastos restan.', max_digits=14)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inmuebles.liquidacion')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inmuebles.unidad')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GastoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_usd', apps.inmuebles.models.Monto(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('comprobante', models.FileField(blank=True, null=True, upload_to=apps.inmuebles.models.ruta_gastos)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='proveedores.proveedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('liquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='inmuebles.liquidacion')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_propiedad', to='inmuebles.unidad')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='inmuebles.unidad'),
        ),
        migrations.CreateModel(
            name='ConsultaPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('contactada', 'Contactada'), ('cerrada', 'Cerrada')], default='nueva', max_length=12)),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='inmuebles.unidad')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='inmuebles.unidad'),
        ),
        migrations.CreateModel(
            name='UnidadFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=apps.inmuebles.models.ruta_fotos)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('es_portada', models.BooleanField(default=False)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inmuebles.unidad')),
            ],
            options={
                'ordering': ['-es_portada', 'orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='periodocondominio',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'anulado'), _negated=True), fields=('edificio', 'periodo'), name='uniq_periodo_edificio_vigente'),
        ),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(condition=models.Q(('edificio__isnull', False)), fields=('edificio', 'codigo'), name='uniq_unidad_edificio_codigo'),
        ),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(condition=models.Q(('edificio__isnull', True)), fields=('codigo',), name='uniq_unidad_suelta_codigo'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='idx_cargo_estado_venc'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['unidad', 'estado'], name='idx_cargo_unidad_estado'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(condition=models.Q(('periodo_condominio__isnull', False), models.Q(('estado', 'anulado'), _negated=True)), fields=('periodo_condominio', 'unidad'), name='uniq_cargo_periodo_unidad'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(condition=models.Q(('contrato__isnull', False), ('tipo', 'canon'), models.Q(('estado', 'anulado'), _negated=True)), fields=('contrato', 'periodo', 'tipo'), name='uniq_cargo_canon_contrato_periodo'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'mora'), models.Q(('estado', 'anulado'), _negated=True)), fields=('cargo_origen', 'periodo'), name='uniq_cargo_mora_origen_periodo'),
        ),
    ]
