# Generated by Django 5.1 on 2026-05-13 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_sucursal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de Asistencia', 'verbose_name_plural': 'Registros de Asistencia'},
        ),
        migrations.AlterModelOptions(
            name='descanso',
            options={'ordering': ['-inicio_descanso'], 'verbose_name': 'Descanso', 'verbose_name_plural': 'Descansos'},
        ),
        migrations.AlterModelOptions(
            name='diafestivo',
            options={'ordering': ['fecha'], 'verbose_name': 'Día Festivo', 'verbose_name_plural': 'Días Festivos'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Festivo', 'Festivo'), ('Medio Día', 'Medio Día')], default='Presente', max_length=20, verbose_name='Estado del Día'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado_actual',
            field=models.CharField(default='out', help_text='Estado en tiempo real: out, in, break', max_length=10, verbose_name='Estado Actual'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_entrada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_salida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='llegada_tarde',
            field=models.BooleanField(default=False, verbose_name='Llegada Tarde'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='descanso',
            name='asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descansos', to='rrhh.asistencia', verbose_name='Asistencia Asociada'),
        ),
        migrations.AlterField(
            model_name='descanso',
            name='fin_descanso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin del Descanso'),
        ),
        migrations.AlterField(
            model_name='descanso',
            name='inicio_descanso',
            field=models.DateTimeField(verbose_name='Inicio del Descanso'),
        ),
        migrations.AlterField(
            model_name='diafestivo',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='diafestivo',
            name='fecha',
            field=models.DateField(unique=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_entrada_oficial',
            field=models.TimeField(verbose_name='Hora de Entrada Oficial'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_salida_oficial',
            field=models.TimeField(verbose_name='Hora de Salida Oficial'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='margen_tardanza_minutos',
            field=models.PositiveIntegerField(default=5, help_text='Minutos de tolerancia para llegar tarde', verbose_name='Margen de Tardanza (minutos)'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='nombre',
            field=models.CharField(default='Horario General', max_length=100, verbose_name='Nombre del Horario'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Sucursal'),
        ),
    ]
