# Generated by Django 5.1.15 on 2026-09-24 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_departamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pagada', 'Pagada')], default='borrador', max_length=10)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'verbose_name_plural': 'Períodos de Nómina',
                'db_table': 'PeriodoNomina',
                'ordering': ['-fecha_desde'],
            },
        ),
        migrations.CreateModel(
            name='NominaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dias_ausencia', models.PositiveIntegerField(default=0)),
                ('deduccion_ausencias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otras_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='rrhh.periodonomina')),
            ],
            options={
                'verbose_name': 'Línea de Nómina',
                'verbose_name_plural': 'Líneas de Nómina',
                'db_table': 'NominaEmpleado',
                'unique_together': {('periodo', 'usuario')},
            },
        ),
    ]
