# Generated by Django 5.1 on 2026-09-24 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_periodonomina_nominaempleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('bono', 'Bono / Asignación'), ('deduccion', 'Deducción')], max_length=10)),
                ('modo', models.CharField(choices=[('porcentaje', 'Porcentaje del sueldo base'), ('fijo', 'Monto fijo')], default='fijo', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Porcentaje del sueldo base (ej. 4.00 = 4%) o monto fijo, según `modo`.', max_digits=12)),
                ('recurrente', models.BooleanField(default=True, help_text='Si está activo, se aplica automáticamente a cada nómina nueva de cada empleado.')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concepto de Nómina',
                'verbose_name_plural': 'Conceptos de Nómina',
                'db_table': 'ConceptoNomina',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='nominaempleado',
            name='horas_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas Extra'),
        ),
        migrations.AddField(
            model_name='nominaempleado',
            name='pago_horas_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pago por Horas Extra'),
        ),
        migrations.CreateModel(
            name='NominaEmpleadoConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('bono', 'Bono / Asignación'), ('deduccion', 'Deducción')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rrhh.conceptonomina')),
                ('nomina_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='rrhh.nominaempleado')),
            ],
            options={
                'verbose_name': 'Concepto Aplicado a Nómina',
                'verbose_name_plural': 'Conceptos Aplicados a Nómina',
                'db_table': 'NominaEmpleadoConcepto',
            },
        ),
    ]
