# Generated by Django 5.1.15 on 2026-09-26 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_nominaempleadoconcepto_concepto_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_vacaciones_por_anio', models.PositiveIntegerField(default=15, help_text='Días de vacaciones que acumula un empleado por cada año completo de antigüedad.')),
                ('dias_prestaciones_por_anio', models.PositiveIntegerField(default=15, help_text="Días de sueldo que se acreditan como 'prestaciones sociales' (o equivalente) por cada año completo de antigüedad -- se usa solo como referencia al calcular una liquidación.")),
                ('dias_periodo_sueldo_base', models.PositiveIntegerField(default=30, help_text="A cuántos días representa el 'Sueldo Base' del empleado (ej. 30 si es mensual, 15 si es quincenal) -- de aquí se deriva el sueldo diario usado en vacaciones y liquidaciones.")),
            ],
            options={
                'verbose_name': 'Configuración de RRHH',
                'verbose_name_plural': 'Configuración de RRHH',
            },
        ),
        migrations.CreateModel(
            name='VacacionTomada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField(help_text='Días calendario del período (fecha_fin - fecha_inicio + 1).')),
                ('observaciones', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones_tomadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacación Tomada',
                'verbose_name_plural': 'Vacaciones Tomadas',
                'db_table': 'VacacionTomada',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
