# Generated by Django 5.1 on 2026-09-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('accion', models.CharField(choices=[('crear', 'Creación'), ('actualizar', 'Actualización'), ('eliminar', 'Baja / eliminación'), ('reactivar', 'Reactivación')], db_index=True, max_length=20)),
                ('modelo', models.CharField(db_index=True, help_text="Nombre del modelo afectado, ej. 'Factura'.", max_length=100)),
                ('objeto_id', models.CharField(blank=True, default='', max_length=50)),
                ('objeto_repr', models.CharField(blank=True, default='', help_text="Representación legible, ej. 'Factura F-011'.", max_length=255)),
                ('cambios', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'db_table': 'RegistroAuditoria',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['modelo', 'objeto_id'], name='RegistroAud_modelo_ab39fc_idx')],
            },
        ),
    ]
