# Generated by Django 5.1.15 on 2026-09-20 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_alter_nivelprecio_options_and_more'),
        ('facturacion', '0016_factura_pendiente_de_aprobacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('equipo', models.CharField(help_text='Ej. "Laptop HP Pavilion", "Nevera Whirlpool".', max_length=255, verbose_name='Equipo/artículo')),
                ('descripcion_falla', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_proceso', 'En Proceso'), ('listo', 'Listo para Entregar'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='recibido', max_length=15)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio', to='clientes.cliente')),
                ('factura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_servicio', to='facturacion.factura')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_servicio_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OrdenServicio',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
