# Generated by Django 5.1.15 on 2026-09-20 18:30, hand-edited: el campo es
# `unique=True` pero ya puede haber órdenes existentes -- agregarlo
# directamente como único con default '' rompería la restricción de
# unicidad en cualquier tenant con más de una orden (todas competirían por
# el mismo '' vacío). Se agrega sin la restricción, se rellena un token
# distinto por fila, y RECIÉN AHÍ se activa `unique=True`.
import secrets

from django.db import migrations, models


def backfill_tokens(apps, schema_editor):
    OrdenServicio = apps.get_model('servicios', 'OrdenServicio')
    for orden in OrdenServicio.objects.filter(token_publico='').iterator():
        orden.token_publico = secrets.token_urlsafe(24)
        orden.save(update_fields=['token_publico'])


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='token_publico',
            field=models.CharField(blank=True, editable=False, max_length=64, default=''),
        ),
        migrations.RunPython(backfill_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ordenservicio',
            name='token_publico',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
