# Generated by Django 5.1.15 on 2026-09-24 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_departamento'),
        ('servicios', '0002_ordenservicio_token_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rrhh.departamento'),
        ),
    ]
