# Generated by Django 5.1 on 2026-05-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupondescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valido_desde', models.DateField()),
                ('valido_hasta', models.DateField()),
                ('usos_maximos', models.IntegerField(blank=True, null=True)),
                ('usos_actuales', models.IntegerField(blank=True, null=True)),
                ('minimo_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'CuponDescuento',
            },
        ),
        migrations.CreateModel(
            name='Detallefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_linea', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'DetalleFactura',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('monto_reembolso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Devolucion',
            },
        ),
        migrations.CreateModel(
            name='Direccionenvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('codigo_postal', models.CharField(max_length=5)),
                ('provincia', models.CharField(max_length=50)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('predeterminada', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DireccionEnvio',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('transportista', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_seguimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Envio',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateTimeField()),
                ('correlativo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_global', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('nif_factura', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre_cliente_pendiente', models.CharField(blank=True, max_length=100, null=True)),
                ('comentario_pendiente', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='Facturaelectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.CharField(max_length=50)),
                ('qr_code', models.BinaryField()),
                ('firma_electronica', models.TextField()),
                ('fecha_registro_aeat', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'FacturaElectronica',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nro_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_metodo', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'MetodoPago',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_operacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_producto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direccion_envio', models.TextField(blank=True, null=True)),
                ('transaccion_id', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('correlativo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'Orden',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('max_usos', models.IntegerField(blank=True, null=True)),
                ('usos_actuales', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Promocion',
            },
        ),
        migrations.CreateModel(
            name='Transaccionpago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
                ('codigo_transaccion', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TransaccionPago',
            },
        ),
    ]
