# Generated by Django 5.1 on 2026-05-24 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_moneda_tasacambio'),
        ('proveedores', '0001_initial'),
        ('facturacion', '0003_alter_detallefactura_iva_linea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero_control',
            field=models.CharField(blank=True, help_text='Número de control SENIAT de la factura.', max_length=50, null=True, verbose_name='Número de Control'),
        ),
        migrations.AddField(
            model_name='factura',
            name='base_imponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base Imponible'),
        ),
        migrations.AddField(
            model_name='factura',
            name='retencion_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retención Total'),
        ),
        migrations.AddField(
            model_name='factura',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.moneda', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tasa_cambio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Tasa aplicada a la moneda de la factura frente a la base.', max_digits=20, null=True, verbose_name='Tasa de Cambio'),
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50, unique=True, verbose_name='Número de Nota')),
                ('numero_control', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Control')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base Imponible')),
                ('iva_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('retencion_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retención')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas_credito', to='facturacion.factura', verbose_name='Factura Asociada')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'db_table': 'NotaCredito',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='NotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50, unique=True, verbose_name='Número de Nota')),
                ('numero_control', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Control')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base Imponible')),
                ('iva_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas_debito', to='facturacion.factura', verbose_name='Factura Asociada')),
            ],
            options={
                'verbose_name': 'Nota de Débito',
                'verbose_name_plural': 'Notas de Débito',
                'db_table': 'NotaDebito',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='LibroCompraVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_libro', models.CharField(choices=[('compra', 'Libro de Compra'), ('venta', 'Libro de Venta')], max_length=10, verbose_name='Tipo de Libro')),
                ('fecha_operacion', models.DateField(verbose_name='Fecha de Operación')),
                ('tipo_documento', models.CharField(help_text='Ej: Factura, Nota de Crédito, Nota de Débito', max_length=50, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('numero_control', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Control')),
                ('rif', models.CharField(blank=True, max_length=20, null=True, verbose_name='RIF')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base Imponible')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('retencion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retención')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Libro de Compra y Venta',
                'verbose_name_plural': 'Libros de Compra y Venta',
                'db_table': 'LibroCompraVenta',
                'ordering': ['-fecha_operacion'],
                'indexes': [models.Index(fields=['tipo_libro', 'fecha_operacion'], name='idx_libro_fecha')],
            },
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_retencion', models.CharField(choices=[('islr', 'ISLR'), ('iva', 'IVA Retenido'), ('otros', 'Otros')], max_length=10, verbose_name='Tipo de Retención')),
                ('numero_comprobante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Comprobante')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje (%)')),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retenciones', to='facturacion.factura', verbose_name='Factura Asociada')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retenciones', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Comprobante de Retención',
                'verbose_name_plural': 'Comprobantes de Retención',
                'db_table': 'Retencion',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
