# Generated by Django 5.1 on 2026-09-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_seniat_fields_and_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='subtotal_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal (Base)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='base_imponible_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Base Imponible (Base)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='iva_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IVA (Base)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='retencion_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Retención (Base)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total (Base)'),
        ),
    ]
