# Generated by Django 5.1 on 2026-09-11 03:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_factura_moneda_base_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='fecha_registro_aeat',
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de envío'), ('enviado', 'Enviado al proveedor'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('no_soportado', 'Sin proveedor de facturación electrónica para este país')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 11, 3, 5, 1, 552409, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='fecha_procesado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='proveedor_codigo',
            field=models.CharField(blank=True, help_text="Código del InvoicingAdapter que procesó el documento (ej: 'seniat', 'dian', 'sunat').", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='respuesta_proveedor',
            field=models.JSONField(blank=True, help_text='Respuesta cruda del proveedor fiscal, para auditoría/depuración.', null=True),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='csv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CSV / folio fiscal'),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_electronica', to='facturacion.factura'),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='firma_electronica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='qr_code',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
