# Generated by Django 5.1 on 2026-09-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_nivelprecio_options_and_more'),
        ('facturacion', '0007_sql_index_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente_b2b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_b2b', to='clientes.clienteb2b'),
        ),
    ]
