# Generated by Django 5.1.15 on 2026-09-14 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_factura_cliente_b2b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='condicion_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10, verbose_name='Condición de Pago'),
        ),
        migrations.AddField(
            model_name='factura',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Empleado que realizó la venta (puede diferir de `usuario` si otra persona la registra en el sistema).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
