# Generated by Django 5.1 on 2026-09-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_factura_condicion_pago_factura_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionpago',
            name='factura',
            field=models.ForeignKey(blank=True, help_text='Factura/pedido al que corresponde este pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_pago', to='facturacion.factura'),
        ),
        migrations.AddField(
            model_name='transaccionpago',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de pago'),
        ),
    ]
