# Generated by Django 5.1 on 2026-09-14 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_transaccionpago_factura_transaccionpago_referencia'),
        ('inventario', '0008_variacionproducto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.variacionproducto'),
        ),
    ]
