# Generated by Django 5.1.15 on 2026-09-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_alter_detallefactura_variante'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='librocompraventa',
            index=models.Index(fields=['tipo_documento', 'numero_documento'], name='idx_libro_tipo_numero'),
        ),
    ]
