# Generated by Django 5.1.15 on 2026-09-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_librocompraventa_idx_libro_tipo_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='base_imponible_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base Imponible (moneda base)'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='iva_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA (moneda base)'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='retencion_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retención (moneda base)'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total (moneda base)'),
        ),
        migrations.AddField(
            model_name='notadebito',
            name='base_imponible_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base Imponible (moneda base)'),
        ),
        migrations.AddField(
            model_name='notadebito',
            name='iva_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA (moneda base)'),
        ),
        migrations.AddField(
            model_name='notadebito',
            name='total_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total (moneda base)'),
        ),
    ]
