# Generated by Django 5.1.15 on 2026-09-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_notacredito_base_imponible_base_notacredito_iva_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencion',
            name='periodo_imposicion',
            field=models.CharField(blank=True, help_text='Periodo fiscal que declara el proveedor (ej: 2026, 01/2026).', max_length=20, null=True, verbose_name='Periodo de Imposición'),
        ),
    ]
