# Generated by Django 5.1.15 on 2026-09-16 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_configuracioncorrelativo_control_number_length_nota_credito_and_more'),
        ('facturacion', '0014_retencion_periodo_imposicion'),
        ('pagos', '0004_banco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='banco',
            field=models.ForeignKey(blank=True, help_text='Banco al que se acredita este método de pago (vacío para efectivo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metodos_pago', to='pagos.banco'),
        ),
        migrations.AddField(
            model_name='transaccionpago',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccionpago',
            name='vuelto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CajaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones_cierre', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CajaSesion',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='transaccionpago',
            name='caja_sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='facturacion.cajasesion'),
        ),
        migrations.CreateModel(
            name='CajaSesionMonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_apertura', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_cierre_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monto_cierre_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('caja_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montos', to='facturacion.cajasesion')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.moneda')),
            ],
            options={
                'db_table': 'CajaSesionMonto',
                'unique_together': {('caja_sesion', 'moneda')},
            },
        ),
    ]
