# Generated by Django 5.1.15 on 2026-09-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_metodopago_banco_transaccionpago_monto_recibido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pendiente_de_aprobacion',
            field=models.BooleanField(default=False, help_text='True si es un pedido (catálogo/B2B) que todavía no ha sido confirmado por el admin: no debe recibir correlativo ni número de control hasta que se apruebe.', verbose_name='Pendiente de aprobación'),
        ),
    ]
