# Generated by Django 5.1 on 2026-09-24 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_factura_pendiente_de_aprobacion'),
        ('inventario', '0013_alter_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.presentacionproducto'),
        ),
    ]
