# Generated by Django 5.1 on 2026-09-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_detallefactura_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='inventario_afectado',
            field=models.BooleanField(default=False, help_text='True si ya se descontó el stock de esta factura/nota de entrega -- evita descontarlo dos veces o restaurarlo sin haberlo descontado.', verbose_name='Inventario afectado'),
        ),
    ]
