# Generated by Django 5.1 on 2026-09-24 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_configuracionempresa_pin_autorizacion_hash_and_more'),
        ('facturacion', '0019_backfill_inventario_afectado'),
        ('pagos', '0004_banco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('concepto', models.CharField(help_text='Ej: "Depósito del cierre del 24/09 al Banco Mercantil".', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos.banco')),
                ('caja_sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='facturacion.cajasesion')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.moneda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MovimientoCaja',
                'ordering': ['-fecha'],
            },
        ),
    ]
