# Generated by Django 5.1.15 on 2026-09-24 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0020_movimientocaja'),
        ('rrhh', '0004_departamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='departamento_preparacion',
            field=models.ForeignKey(blank=True, help_text='Qué equipo (Almacén, Cocina...) debe preparar este pedido -- opcional, para filtrar la cola de trabajo por estación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rrhh.departamento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado_preparacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de preparar'), ('listo', 'Listo para despacho/entrega')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_preparado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='preparado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
