# Generated by Django 5.1 on 2026-10-02 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_alter_asientocontable_origen_and_more'),
        ('facturacion', '0021_factura_departamento_preparacion_and_more'),
        ('proveedores', '0005_facturacompra_cuentaporpagar_factura_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librocompraventa',
            name='factura_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_libro', to='proveedores.facturacompra'),
        ),
        migrations.AddField(
            model_name='retencion',
            name='asiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.asientocontable'),
        ),
        migrations.AddField(
            model_name='retencion',
            name='factura_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retenciones', to='proveedores.facturacompra', verbose_name='Factura de Compra'),
        ),
    ]
