# Generated by Django 5.1 on 2026-05-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=10)),
                ('documento', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
    ]
