# Generated by Django 5.1 on 2026-05-01 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usermetadata'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('tipo_documento', 'documento')},
        ),
    ]
