# Generated by Django 5.1 on 2026-05-24 18:47

import apps.clientes.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_options_alter_cliente_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único para el nivel de precio. Ej: Mayorista', max_length=100, unique=True)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento global para este nivel (ej: 15.00 para 15%)', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nivel de Precio',
                'verbose_name_plural': 'Niveles de Precios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('tipo_documento', 'documento')},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, help_text='Número de documento de identidad del cliente.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('V', 'Cédula Venezolana'), ('E', 'Cédula Extranjero'), ('J', 'RIF Jurídico'), ('G', 'RIF Gubernamental'), ('P', 'Pasaporte')], help_text='Tipo de documento de identidad del cliente.', max_length=1, null=True),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.CreateModel(
            name='ClienteB2B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(help_text='Nombre legal o comercial de la empresa cliente.', max_length=255)),
                ('rif', models.CharField(help_text='Registro de Identificación Fiscal (o equivalente local).', max_length=20, unique=True)),
                ('email_contacto', models.EmailField(help_text='Email principal para comunicaciones y para la invitación.', max_length=254, unique=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=30)),
                ('direccion_fiscal', models.TextField(blank=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto máximo de crédito otorgado.', max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Activación'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Usuario para iniciar sesión en el portal B2B. Nulo hasta la activación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_b2b', to=settings.AUTH_USER_MODEL)),
                ('nivel_precio', models.ForeignKey(help_text='Categoría de precios asignada a este cliente.', on_delete=django.db.models.deletion.PROTECT, related_name='clientes_b2b', to='clientes.nivelprecio')),
            ],
            options={
                'verbose_name': 'Cliente B2B',
                'verbose_name_plural': 'Clientes B2B',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='InvitacionB2B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email al que se envió la invitación. Se mantiene por referencia.', max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_expiracion', models.DateTimeField(default=apps.clientes.models.default_expiration)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('utilizada', models.BooleanField(default=False)),
                ('cliente_b2b', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitacion', to='clientes.clienteb2b')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
