# Generated by Django 5.1 on 2026-09-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_nivelprecio_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelprecio',
            options={'ordering': ['monto_minimo_periodo', 'nombre'], 'verbose_name': 'Nivel de Precio', 'verbose_name_plural': 'Niveles de Precios'},
        ),
        migrations.AddField(
            model_name='clienteb2b',
            name='nivel_precio_actualizado_en',
            field=models.DateTimeField(blank=True, help_text='Última vez que el sistema subió automáticamente el nivel de precio por volumen de compra.', null=True),
        ),
        migrations.AddField(
            model_name='nivelprecio',
            name='monto_minimo_periodo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto mínimo comprado por un cliente en el período de evaluación (ver `pricing_tier_service.PERIODO_EVALUACION_MESES`) para calificar automáticamente a este nivel. 0 = nivel de entrada, sin mínimo.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='clienteb2b',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto máximo de crédito otorgado. 0 = sin línea de crédito configurada (no se restringe el pedido).', max_digits=12),
        ),
    ]
