# Generated by Django 5.1.15 on 2026-09-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_nivelprecio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contribuyente_especial',
            field=models.BooleanField(default=False, help_text='Venezuela: cliente calificado por el SENIAT como agente de retención de IVA.', verbose_name='Contribuyente especial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dias_credito',
            field=models.PositiveIntegerField(blank=True, help_text='A cuántos días le das crédito a este cliente (vacío = sin crédito definido).', null=True, verbose_name='Días de crédito'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('V', 'Cédula Venezolana'), ('E', 'Cédula Extranjero'), ('J', 'RIF Jurídico'), ('G', 'RIF Gubernamental'), ('P', 'Pasaporte'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT (Persona Jurídica)'), ('DNI', 'DNI'), ('RUC', 'RUC (Persona Jurídica)')], help_text='Tipo de documento de identidad del cliente.', max_length=5, null=True),
        ),
    ]
