# Generated by Django 5.1 on 2026-05-10 22:10

from django.db import migrations

def create_public_tenant_and_domains(apps, schema_editor):
    # Usamos apps.get_model para evitar problemas de importación circular
    Client = apps.get_model('tenants', 'Client')
    Domain = apps.get_model('tenants', 'Domain')

    # 1. Crear o recuperar el esquema público
    # Usamos nombre_empresa que es el campo de tu modelo
    tenant, created = Client.objects.get_or_create(
        schema_name='public',
        defaults={
            'nombre_empresa': 'Administración SaaS', 
            'email_contacto': 'admin@power.com',
            'esta_activo': True
        }
    )

    # 2. Registrar localhost como primario
    Domain.objects.get_or_create(
        domain='localhost',
        tenant=tenant,
        defaults={'is_primary': True}
    )

    # 3. Registrar 127.0.0.1 como secundario
    Domain.objects.get_or_create(
        domain='127.0.0.1',
        tenant=tenant,
        defaults={'is_primary': False}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_plan_remove_client_plan_subscription'),
    ]

    operations = [
        migrations.RunPython(create_public_tenant_and_domains),
    ]