# Generated by Django 5.1 on 2026-05-18 01:44
# Reescrita durante la auditoría de arquitectura: el `default=1` original
# rompía la creación de cualquier base de datos nueva (test DB, clon del
# repo) porque en un esquema recién creado no existe todavía ningún
# `auth_user` con id=1. En la base de datos real esta migración ya estaba
# aplicada (no se vuelve a ejecutar); este cambio solo afecta a bases de
# datos que arrancan de cero.
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def asignar_owner_temporal(apps, schema_editor):
    """
    Asigna un owner a cualquier `Client` preexistente sin uno (ej. el tenant
    'public' sembrado por la migración de datos anterior), usando el primer
    superusuario disponible o creando uno de sistema si no existe ninguno.
    """
    Client = apps.get_model('tenants', 'Client')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    if not Client.objects.filter(owner__isnull=True).exists():
        return

    owner = User.objects.filter(is_superuser=True).order_by('id').first()
    if owner is None:
        owner = User.objects.create(
            username='system',
            email='system@localhost',
            is_staff=True,
            is_superuser=True,
        )
    Client.objects.filter(owner__isnull=True).update(owner_id=owner.id)


def noop_reverse(apps, schema_editor):
    """No hay nada que revertir de forma segura: se deja tal cual."""


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_auto_20260510_2210'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(asignar_owner_temporal, noop_reverse),
        migrations.AlterField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
