# Generated by Django 5.1 on 2026-05-24 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_client_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='client',
            name='onboarding_completado',
            field=models.BooleanField(default=False, help_text='Indica si el inquilino ha completado el asistente de configuración inicial.'),
        ),
        migrations.AddField(
            model_name='client',
            name='tipo_negocio',
            field=models.CharField(choices=[('retail', 'Retail (Venta al Detal)'), ('b2b', 'B2B (Mayorista/Fabricante)')], default='retail', help_text='Modelo de negocio principal del inquilino.', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limite_sucursales',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limite_usuarios',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='estado',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.plan'),
        ),
    ]
