# Generated by Django 5.1 on 2026-09-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_remove_plan_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pais_codigo',
            field=models.CharField(choices=[('VE', 'Venezuela'), ('CO', 'Colombia'), ('PE', 'Perú')], default='VE', help_text='País de operación del inquilino. Determina moneda base, IVA e impuestos aplicables desde el alta.', max_length=2),
        ),
    ]
