# Generated by Django 5.1 on 2026-09-12 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_client_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_movil_banco', models.CharField(blank=True, default='', max_length=100)),
                ('pago_movil_cedula', models.CharField(blank=True, default='', max_length=20)),
                ('pago_movil_telefono', models.CharField(blank=True, default='', max_length=20)),
                ('zelle_email', models.EmailField(blank=True, default='', max_length=254)),
                ('zelle_titular', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_publishable_key', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Cobro de la Plataforma',
                'verbose_name_plural': 'Configuración de Cobro de la Plataforma',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, help_text="Identificador estable usado por el frontend (ej: 'emprendedor', 'pro'). No cambia aunque se edite el nombre visible.", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('pago_movil', 'Pago Móvil'), ('zelle', 'Zelle'), ('stripe', 'Stripe')], max_length=20)),
                ('referencia', models.CharField(blank=True, default='', help_text='Número de referencia reportado por el cliente (Pago Móvil/Zelle).', max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_suscripcion', to='tenants.client')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.plan')),
            ],
            options={
                'verbose_name': 'Pago de Suscripción',
                'verbose_name_plural': 'Pagos de Suscripción',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
