# Generated by Django 5.1 on 2026-09-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_platformpaymentconfig_plan_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_registros_gratis', models.PositiveIntegerField(blank=True, help_text='Máximo de tenants que pueden registrarse en total (todos arrancan en el plan de prueba). Vacío = sin límite.', null=True)),
                ('dias_gracia_tras_vencimiento', models.PositiveIntegerField(default=3, help_text='Días tras vencer la suscripción antes de bloquear el acceso al panel del tenant.')),
            ],
            options={
                'verbose_name': 'Configuración de la Plataforma',
                'verbose_name_plural': 'Configuración de la Plataforma',
            },
        ),
    ]
