# Generated by Django 5.1 on 2026-09-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='limite_productos',
            field=models.PositiveIntegerField(blank=True, help_text='Máximo de productos activos que puede tener el tenant. Vacío = sin límite.', null=True),
        ),
    ]
