# Generated by Django 5.1 on 2026-09-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_plan_limite_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='periodo',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensual', max_length=20),
        ),
    ]
