# Generated by Django 5.1.15 on 2026-09-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_alter_client_tipo_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tipo_negocio',
            field=models.CharField(choices=[('retail', 'Retail (Venta al Detal)'), ('b2b', 'B2B (Mayorista/Fabricante)'), ('restaurante', 'Restaurante / Bar'), ('farmacia', 'Farmacia'), ('servicios', 'Taller / Servicios'), ('contador', 'Contador / Firma Contable')], default='retail', help_text='Modelo de negocio principal del inquilino.', max_length=20),
        ),
    ]
