# Generated by Django 5.1.15 on 2026-09-20 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_client_tipo_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tipos_negocio',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Tipos de negocio a los que aplica este plan. Vacío = aplica a todos.', size=None),
        ),
    ]
