# Generated by Django 5.1 on 2026-09-25 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_plan_tipos_negocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de conversión'), ('recompensado', 'Recompensado')], default='pendiente', max_length=15)),
                ('meses_bonus', models.PositiveIntegerField(default=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_recompensa', models.DateTimeField(blank=True, null=True)),
                ('referente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referidos_hechos', to='tenants.client')),
                ('referido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referido_de', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Referido',
                'verbose_name_plural': 'Referidos',
                'db_table': 'Referido',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
