# Generated by Django 5.1 on 2026-09-26 18:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0016_referido"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="modulos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=40),
                blank=True,
                default=list,
                help_text="Módulos incluidos en el plan. Vacío = todos.",
                size=None,
            ),
        ),
    ]
