# Generated by Django 5.1 on 2026-10-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_plan_modulo_facturas_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='limite_unidades',
            field=models.PositiveIntegerField(blank=True, help_text='Máximo de unidades/propiedades activas (condominios e inmobiliaria). Vacío = sin límite.', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tipo_negocio',
            field=models.CharField(choices=[('retail', 'Retail (Venta al Detal)'), ('b2b', 'B2B (Mayorista/Fabricante)'), ('restaurante', 'Restaurante / Bar'), ('farmacia', 'Farmacia'), ('servicios', 'Taller / Servicios'), ('contador', 'Contador / Firma Contable'), ('condominios', 'Administradora de Condominios'), ('inmobiliaria', 'Inmobiliaria')], default='retail', help_text='Modelo de negocio principal del inquilino.', max_length=20),
        ),
    ]
