# Generated by Django 5.1 on 2026-05-01 23:49

import apps.inventario.models
import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('facturacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(blank=True, choices=[('AND', 'Andalucía'), ('ARA', 'Aragón'), ('AST', 'Asturias'), ('BAL', 'Baleares'), ('CAN', 'Canarias'), ('CANT', 'Cantabria'), ('CLM', 'Castilla-La Mancha'), ('CYL', 'Castilla y León'), ('CAT', 'Cataluña'), ('EXT', 'Extremadura'), ('GAL', 'Galicia'), ('RIA', 'La Rioja'), ('MAD', 'Madrid'), ('MUR', 'Murcia'), ('NAV', 'Navarra'), ('PV', 'País Vasco'), ('VAL', 'Valencia')], default='CYL', max_length=4, null=True)),
            ],
            options={
                'db_table': 'Almacen',
            },
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_envio', models.CharField(max_length=50)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_kg_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiempo_entrega', models.CharField(max_length=20)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Transportista',
            },
        ),
        migrations.CreateModel(
            name='Categoriaproducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre')),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_creadas', to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.categoriaproducto')),
            ],
            options={
                'db_table': 'CategoriaProducto',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.almacen')),
            ],
            options={
                'db_table': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='Lecturacodigobarras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=50)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.almacen')),
            ],
            options={
                'db_table': 'LecturaCodigoBarras',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('disponible_online', models.BooleanField(blank=True, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sku', models.CharField(blank=True, help_text='Código único de producto (SKU), usado para sincronizar con otras plataformas.', max_length=100, null=True, unique=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('tipo', models.CharField(choices=[('simple', 'Simple'), ('variable', 'Variable')], default='simple', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.almacen')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoriaproducto')),
                ('configuracion_iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.configuracioniva')),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
                ('cantidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
            ],
            options={
                'db_table': 'MovimientoInventario',
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto'),
        ),
        migrations.CreateModel(
            name='Reservastock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valido_hasta', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.almacen')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.orden')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'ReservaStock',
            },
        ),
        migrations.CreateModel(
            name='ValorAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=80)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='inventario.atributo')),
            ],
        ),
        migrations.CreateModel(
            name='Variacionproducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('codigo_barras', models.CharField(max_length=50, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.inventario.models.variant_image_upload_to)),
                ('atributos', models.ManyToManyField(to='inventario.valoratributo')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'VariacionProducto',
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('producto', 'almacen')},
        ),
        migrations.CreateModel(
            name='Productocategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.categoriaproducto')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'ProductoCategoria',
                'unique_together': {('producto', 'categoria')},
            },
        ),
    ]
