# Generated by Django 5.1 on 2026-09-11 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_fix_movimientoinventario_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_codigo', models.CharField(choices=[('VE', 'Venezuela'), ('CO', 'Colombia'), ('PE', 'Perú')], max_length=2, verbose_name='País')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'Region',
                'ordering': ['pais_codigo', 'nombre'],
                'unique_together': {('pais_codigo', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='almacen',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Reemplazo multi-país de `estado`. Usar este campo en instalaciones nuevas.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.region', verbose_name='Región/Estado/Departamento'),
        ),
    ]
