# Generated by Django 5.1 on 2026-09-13 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_sql_indices'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('motivo', models.CharField(choices=[('compra_sin_factura', 'Compra con nota de entrega (sin factura)'), ('conteo_fisico', 'Corrección por conteo físico'), ('devolucion_proveedor', 'Devolución a proveedor'), ('merma', 'Merma / producto dañado'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('numero_documento', models.CharField(blank=True, default='', help_text='Número de la nota de entrega/factura física del proveedor, si aplica.', max_length=100)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.almacen')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AjusteInventario',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AjusteInventarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario reportado en la nota de entrega/factura del proveedor (opcional).', max_digits=10, null=True)),
                ('stock_resultante', models.IntegerField(blank=True, null=True)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ajusteinventario')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.variacionproducto')),
            ],
            options={
                'db_table': 'AjusteInventarioDetalle',
            },
        ),
    ]
