# Generated by Django 5.1 on 2026-09-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_ajusteinventario_ajusteinventariodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteinventario',
            name='numero_control',
            field=models.CharField(blank=True, default='', help_text="Número de control SENIAT de la factura fiscal del proveedor (solo aplica cuando el motivo es 'Compra con factura fiscal').", max_length=50),
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='motivo',
            field=models.CharField(choices=[('compra_con_factura', 'Compra con factura fiscal'), ('compra_sin_factura', 'Compra con nota de entrega (sin factura)'), ('conteo_fisico', 'Corrección por conteo físico'), ('devolucion_proveedor', 'Devolución a proveedor'), ('merma', 'Merma / producto dañado'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='numero_documento',
            field=models.CharField(blank=True, default='', help_text='Número de la nota de entrega o de la factura fiscal del proveedor, según el motivo.', max_length=100),
        ),
    ]
