# Generated by Django 5.1.15 on 2026-09-14 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_alter_configuracioncorrelativo_control_number_length_and_more'),
        ('inventario', '0006_ajusteinventario_numero_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.ForeignKey(blank=True, help_text='Moneda en la que se ingresó `precio`. Si se deja vacío, se asume la moneda base del tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='configuracion.moneda'),
        ),
    ]
