# Generated by Django 5.1 on 2026-09-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacionproducto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
