# Generated by Django 5.1 on 2026-09-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_variacionproducto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacionproducto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
