# Generated by Django 5.1.15 on 2026-09-15 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_variacionproducto_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(blank=True, help_text='Umbral de "bajo stock" para este producto. Vacío = usa el umbral general del sistema.', null=True),
        ),
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Unidad, Caja x12, Bulto x50.', max_length=50)),
                ('factor_conversion', models.PositiveIntegerField(default=1, help_text='Cuántas unidades base equivale una unidad de esta presentación (ej: 50 para "Bulto x50").')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Precio final (con IVA incluido) de esta presentación. Vacío = precio unitario × factor.', max_digits=10, null=True)),
                ('es_default', models.BooleanField(default=False, help_text='La presentación preseleccionada al vender (normalmente "Unidad", factor 1).')),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='inventario.producto')),
            ],
            options={
                'db_table': 'PresentacionProducto',
                'ordering': ['factor_conversion'],
            },
        ),
    ]
