# Generated by Django 5.1.15 on 2026-09-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_producto_stock_minimo_presentacionproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusteinventariodetalle',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Costo unitario reportado en la nota de entrega/factura del proveedor (opcional).', max_digits=14, null=True),
        ),
    ]
