# Generated by Django 5.1.15 on 2026-09-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_ajusteinventariodetalle_costo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_insumo',
            field=models.BooleanField(default=False, help_text='Ítem de stock que no se ofrece directamente (ej. materia prima) -- se excluye de los selectores de venta.', verbose_name='Es insumo interno'),
        ),
    ]
