# Generated by Django 5.1.15 on 2026-09-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_producto_es_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('simple', 'Simple'), ('variable', 'Variable'), ('servicio', 'Servicio')], default='simple', max_length=20),
        ),
    ]
