# Generated by Django 5.1.15 on 2026-09-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_bootstrap_inventario_por_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='variacionproducto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
    ]
