# Generated by Django 5.1 on 2026-09-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_producto_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='meses_garantia',
            field=models.PositiveIntegerField(blank=True, help_text='Cuántos meses de garantía tiene este producto al venderse. Vacío = sin garantía rastreada.', null=True, verbose_name='Meses de Garantía'),
        ),
    ]
