# Generated by Django 5.1.15 on 2026-09-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_producto_meses_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteinventario',
            name='fecha_documento',
            field=models.DateField(blank=True, help_text='Fecha del documento del proveedor (nota de entrega/factura). Vacío = se usa la fecha en que se cargó el ajuste.', null=True),
        ),
    ]
