# Generated by Django 5.1.15 on 2026-10-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_ajusteinventario_fecha_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusteinventariodetalle',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Costo unitario reportado en la nota de entrega/factura del proveedor. Nulo solo tiene sentido en una SALIDA (no se usa); en una ENTRADA, `AjusteInventarioSerializer.validate()` lo exige para no dejar el costo promedio del producto sin actualizar.', max_digits=14, null=True),
        ),
    ]
