# Generated by Django 5.1.15 on 2026-10-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_alter_ajusteinventariodetalle_costo_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacionproducto',
            name='atributos',
            field=models.ManyToManyField(blank=True, to='inventario.valoratributo'),
        ),
    ]
