# Generated by Django 5.1 on 2026-10-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_alter_variacionproducto_atributos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusteinventario',
            name='motivo',
            field=models.CharField(choices=[('compra_con_factura', 'Compra con factura fiscal'), ('compra_sin_factura', 'Compra con nota de entrega (sin factura)'), ('conteo_fisico', 'Corrección por conteo físico'), ('inventario_inicial', 'Inventario inicial'), ('merma', 'Merma / producto dañado o vencido'), ('consumo_interno', 'Consumo interno / uso propio'), ('devolucion_proveedor', 'Devolución a proveedor'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
    ]
